project/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),    # /diary
    path('add/', views.AddView.as_view(), name = 'add'),  # /diary/add
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'), # diary/update/1
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'), # diary/delete/1
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'), # diary/detail/1
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

project/diary/models.py
from django.db import models
from django.utils import timezone   # djangoでは、datetime.nowのかわりに、timezone.nowで現在日時・時刻を取得する


class Day(models.Model):
    title = models.CharField('タイトル', max_length = 200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default = timezone.now)

    def __str__(self):
        return self.title

project/diary/forms.py
from django import forms
from .models import Day

# Dayモデルの内容から自動的に作成
class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'  # ('title', 'text, 'date)

project/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from .forms import DayCreateForm
from .models import Day


class IndexView(generic.ListView):
    model = Day
    paginate_by = 3


class AddView(generic.CreateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index') #/diary/


class UpdateView(generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index') #/diary/


class DeleteView(generic.DeleteView):
    model = Day
    success_url = reverse_lazy('diary:index')


class DetailView(generic.DetailView):
    model = Day
    success_url = reverse_lazy('diary:index')

project/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>日記アプリケーション</title>

  </head>
  <body>
    <div class="container">
      <nav class = "nav">
        <!-- ページ遷移の場合は、urlタグを使った逆引きがおすすめです。-->
        <a class="nav-link" href = "{% url 'diary:index' %}">一覧</a>
        <a class="nav-link" href = "{% url 'diary:add' %}">追加</a>
      </nav>
      {% block content %}
      {% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

project/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}

<form action="" method="POST">
    <table class="table">
        <tr>
            <th>{{ day.title.label }}</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
            
        </tr>
    </table>

    <p>こちらのボタンタブを削除します。</p>
    <button type = "submit" class = "btn btn-primary">送信</button>
    {% csrf_token %}
</form>

{% endblock %}

project/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}

    <table class="table">
        <tr>
            <th>{{ day.title.label }}</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text | linebreaksbr}}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>

{% endblock %}

project/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}

<p>{{day.title}}</p>
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>{{ form.title.label }}</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>
    <button type = "submit" class = "btn btn-primary">送信</button>
    {% csrf_token %}
</form>

{% endblock %}

project/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>

<table class="table">

<thead>
    <tr>
        <th>タイトル</th>
        <th>日付</th>
    </tr>
</thead>

    <tbody>
        {% for day in day_list %}
    </tbody>
    <tr>
        <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
        <td>{{ day.date }}</td>
        <td><a href = "{% url 'diary:update' day.pk %}">更新</a></td>
        <td><a href = "{% url 'diary:delete' day.pk %}">削除</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% include 'diary/page1.html' %}

{% endblock %}

project/diary/templates/diary/page1.html
<!-- 前へ の部分 -->
<!-- templateでif文を使用する場合はifタグを記載すること -->
{% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">前へ</a>
{% endif %}

<!-- 次へ の部分 -->
{% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">次へ</a>
{% endif %}